### ISSUE TITLE
Support for Docker, `armv7` platform

### ISSUE THREAD

**Issue by tilusnet** [HumanSignal/label-studio#1900]
**Is your feature request related to a problem? Please describe.**
The docker installation doesn't run on a Raspberry Pi / armv7 platform.

**Describe the solution you'd like**
I'd like to install the software in docker on armv7 / Raspberry Pi.

**Comment by tilusnet** [comment]
FYI, I kick started an `armv7` image build from source with `DOCKER_BUILDKIT=1 docker build -t heartexlabs/label-studio:latest .` The build failed after about 15 minutes with:
```
#15 874.3 Collecting psycopg2-binary==2.9.1
#15 874.3   Downloading psycopg2-binary-2.9.1.tar.gz (380 kB)
#15 874.6   Preparing metadata (setup.py): started
#15 875.2   Preparing metadata (setup.py): finished with status 'error'
#15 875.2   ERROR: Command errored out with exit status 1:
#15 875.2    command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eafholdb/psycopg2-binary_31acf8ea5a8c4e888d6f03610144b6a6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eafholdb/psycopg2-binary_31acf8ea5a8c4e888d6f03610144b6a6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xrqta43j
#15 875.2        cwd: /tmp/pip-install-eafholdb/psycopg2-binary_31acf8ea5a8c4e888d6f03610144b6a6/
#15 875.2   Complete output (23 lines):
#15 875.2   running egg_info
#15 875.2   creating /tmp/pip-pip-egg-info-xrqta43j/psycopg2_binary.egg-info
#15 875.2   writing /tmp/pip-pip-egg-info-xrqta43j/psycopg2_binary.egg-info/PKG-INFO
#15 875.2   writing dependency_links to /tmp/pip-pip-egg-info-xrqta43j/psycopg2_binary.egg-info/dependency_links.txt
#15 875.2   writing top-level names to /tmp/pip-pip-egg-info-xrqta43j/psycopg2_binary.egg-info/top_level.txt
#15 875.2   writing manifest file '/tmp/pip-pip-egg-info-xrqta43j/psycopg2_binary.egg-info/SOURCES.txt'
#15 875.2   
#15 875.2   Error: pg_config executable not found.
#15 875.2   
#15 875.2   pg_config is required to build psycopg2 from source.  Please add the directory
#15 875.2   containing pg_config to the $PATH or specify the full executable path with the
#15 875.2   option:
#15 875.2   
#15 875.2       python setup.py build_ext --pg-config /path/to/pg_config build ...
#15 875.2   
#15 875.2   or with the pg_config option in 'setup.cfg'.
#15 875.2   
#15 875.2   If you prefer to avoid building psycopg2 from source, please install the PyPI
#15 875.2   'psycopg2-binary' package instead.
#15 875.2   
#15 875.2   For further information please check the 'doc/src/install.rst' file (also at
#15 875.2   <https://www.psycopg.org/docs/install.html>).
#15 875.2   
#15 875.2   ----------------------------------------
#15 875.2 WARNING: Discarding https://files.pythonhosted.org/packages/14/65/223a5b4146b1d5d5ab66f16ef194916a1ed9720da1f118d7bfb60b8f2bea/psycopg2-binary-2.9.1.tar.gz#sha256=b0221ca5a9837e040ebf61f48899926b5783668b7807419e4adae8175a31f773 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#15 875.2 ERROR: Could not find a version that satisfies the requirement psycopg2-binary==2.9.1 (from versions: 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3)
#15 875.2 ERROR: No matching distribution found for psycopg2-binary==2.9.1
------
executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
```

**Comment by tilusnet** [comment]
to leverage wheel files for the platform it's also recommended to set eg. `/etc/pip.conf` to:
```
[global]
extra-index-url=https://www.piwheels.org/simple
```

**Comment by makseq** [comment]
@tilusnet why do you want to install ls on arm? :-)

**Comment by tilusnet** [comment]
Convenience. My docker hosting system is a Raspberry Pi. 
All my docker containers run there.

**Comment by tilusnet** [comment]
I have crafted a `Dockerfile.armv7` file for a start. It installs all dependencies fast.

```
# syntax=docker/dockerfile:1.3
FROM arm32v7/ubuntu:18.04

ARG PYTHON_VERSION=3.7

# Ubuntu 18.04 comes with Python 3.6 as default, but we upgrade it to 3.7.
# Python 3.7 is the version of choice because piwheels.org provides armv7 wheels for Python 3.7 and 3.9 only.
# Python and pip must be in line at version 3.7, otherwise pip will not match the wheels.
# Python 3.9 is not recommended by Label Studio.

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_CACHE_DIR=/.cache \
    PIP_EXTRA_INDEX_URL=https://www.piwheels.org/simple \
    DJANGO_SETTINGS_MODULE=core.settings.label_studio \
    LABEL_STUDIO_BASE_DATA_DIR=/label-studio/data \
    SETUPTOOLS_USE_DISTUTILS=stdlib

WORKDIR /label-studio

# install packages
RUN set -eux; \
    apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    build-essential postgresql-client libatlas-base-dev libmysqlclient-dev libpq-dev mysql-client \
    python${PYTHON_VERSION} python3-pip python${PYTHON_VERSION}-dev \
    uwsgi git libxml2-dev libxslt-dev zlib1g-dev \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 \
    && python3 -m pip install --upgrade pip
    
# Copy and install middleware dependencies
COPY deploy/requirements-mw.txt /label-studio
RUN --mount=type=cache,target=$PIP_CACHE_DIR \
    pip3 install -r requirements-mw.txt

# Copy and install requirements.txt first for caching
COPY deploy/requirements.txt /label-studio
RUN --mount=type=cache,target=$PIP_CACHE_DIR \
    pip3 install -r requirements.txt

COPY . /label-studio

RUN --mount=type=cache,target=$PIP_CACHE_DIR \
    pip3 install .
    
EXPOSE 8080
RUN ./deploy/prebuild_wo_frontend.sh

ENTRYPOINT ["./deploy/docker-entrypoint.sh"]
CMD ["label-studio"]
```

**Comment by tilusnet** [comment]
I progressed further with additional dependency libraries -- seems to be coming from PIL:
```
# install packages
RUN set -eux; \
    apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    build-essential postgresql-client libatlas-base-dev libmysqlclient-dev libpq-dev mysql-client \
    python${PYTHON_VERSION} python3-pip python${PYTHON_VERSION}-dev \
    libffi-dev \
    libfreetype6-dev \
    libharfbuzz-dev \
    libjpeg-turbo-progs \
    libjpeg62-dev \
    liblcms2-dev \
    libopenjp2-7-dev \
    libtiff5 \
    libwebp-dev \
    tcl8.6-dev \
    tk8.6-dev \
    libc6-dev \
    uwsgi git libxml2-dev libxslt-dev zlib1g-dev \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 \
    && python3 -m pip install --upgrade pip
```

I am now stuck at
```
 => ERROR [stage-0 10/10] RUN ./deploy/prebuild_wo_frontend.sh                                                                                                                           5.7s 
------                                                                                                                                                                                        
 > [stage-0 10/10] RUN ./deploy/prebuild_wo_frontend.sh:                                                                                                                                      
#18 0.939 SCRIPT_DIR: /label-studio/deploy                                                                                                                                                    
#18 0.939 => Collect static...                                                                                                                                                                
#18 2.132 => Database and media directory: /label-studio/data                                                                                                                                 
#18 2.133 => Static URL is set to: /static/                                                                                                                                                   
#18 3.031 Starting new HTTPS connection (1): pypi.org:443
#18 3.090 https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 43122
#18 3.132 Can't read version file: version_.py
#18 3.136 No module named 'version_'
#18 5.089 Traceback (most recent call last):
#18 5.089   File "/label-studio/deploy/../label_studio/manage.py", line 22, in <module>
#18 5.089     execute_from_command_line(sys.argv)
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
#18 5.089     utility.execute()
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
#18 5.089     django.setup()
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
#18 5.089     apps.populate(settings.INSTALLED_APPS)
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
#18 5.089     app_config.import_models()
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
#18 5.089     self.models_module = import_module(models_module_name)
#18 5.089   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
#18 5.089     return _bootstrap._gcd_import(name[level:], package, level)
#18 5.089   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
#18 5.089   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#18 5.089   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#18 5.089   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
#18 5.089   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
#18 5.089   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#18 5.089   File "/label-studio/label_studio/io_storages/models.py", line 5, in <module>
#18 5.089     from .azure_blob.models import AzureBlobImportStorage, AzureBlobImportStorageLink, AzureBlobExportStorage, AzureBlobExportStorageLink
#18 5.089   File "/label-studio/label_studio/io_storages/azure_blob/models.py", line 15, in <module>
#18 5.089     from azure.storage.blob import BlobServiceClient, generate_blob_sas, BlobSasPermissions
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/__init__.py", line 10, in <module>
#18 5.089     from ._blob_client import BlobClient
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_blob_client.py", line 27, in <module>
#18 5.089     from ._shared.encryption import generate_blob_encryption_data
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_shared/encryption.py", line 19, in <module>
#18 5.089     from cryptography.hazmat.primitives.padding import PKCS7
#18 5.089   File "/usr/local/lib/python3.7/dist-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
#18 5.089     from cryptography.hazmat.bindings._rust import (
#18 5.089 ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/dist-packages/cryptography/hazmat/bindings/_rust.abi3.so)
------
executor failed running [/bin/sh -c ./deploy/prebuild_wo_frontend.sh]: exit code: 1
```

**Comment by tilusnet** [comment]
It seems that GLIBC_2.28 is not _explicitly_ supported by the Bionic (18.04) image, but older _and_ newer versions only:

```
root@1bbf8e34f4bf:/label-studio# strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBC_2.4
GLIBC_2.18
GLIBC_2.16
GLIBC_2.17
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by tilusnet** [comment]
thanks @farioas
what's M1?

**Comment by farioas** [comment]
Apple M1 is a series of ARM-based processors made by Apple.
But you could try to build it using armv7 platform

**Comment by tilusnet** [comment]
Is there any particular branch I should try from?
Running from `master` failed:

```
$ DOCKER_BUILDKIT=1 docker build -t heartexlabs/label-studio:latest .

[+] Building 34.0s (8/8) FINISHED                                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                                     0.5s
 => => transferring dockerfile: 1.68kB                                                                                                                                                   0.1s
 => [internal] load .dockerignore                                                                                                                                                        0.4s
 => => transferring context: 250B                                                                                                                                                        0.1s
 => resolve image config for docker.io/docker/dockerfile:1.3                                                                                                                             1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.3@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cfdf59ef1357b3b2                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => ERROR [internal] load metadata for docker.io/library/node:14                                                                                                                        30.3s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                          0.0s
------
 > [internal] load metadata for docker.io/library/node:14:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/14": EOF

```

**Comment by farioas** [comment]
`develop` in mainstream branch

**Comment by tilusnet** [comment]
got further:

```
 => CANCELED [stage-1  5/14] RUN set -eux;     curl -sSL https://nginx.org/keys/nginx_signing.key | apt-key add - &&     echo "deb https://nginx.org/packages/mainline/ubuntu/ $(lsb_r  18.3s
------
 > [frontend-builder 5/5] RUN --mount=type=cache,target=/.npm,uid=1001,gid=0     npm ci  && npm run build:production:
#27 108.1 
#27 108.1 > puppeteer@8.0.0 install /label-studio/label_studio/frontend/node_modules/puppeteer
#27 108.1 > node install.js
#27 108.1 
#27 108.6 **INFO** Skipping browser download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" environment variable was found.
#27 108.9 
#27 108.9 > core-js@2.6.12 postinstall /label-studio/label_studio/frontend/node_modules/core-js
#27 108.9 > node -e "try{require('./postinstall')}catch(e){}"
#27 108.9 
#27 109.2 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#27 109.2 
#27 109.2 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
#27 109.2 > https://opencollective.com/core-js 
#27 109.2 > https://www.patreon.com/zloirock 
#27 109.2 
#27 109.2 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#27 109.2 
#27 111.0 
#27 111.0 > @sentry/cli@1.66.0 install /label-studio/label_studio/frontend/node_modules/@sentry/cli
#27 111.0 > node scripts/install.js
#27 111.0 
#27 111.4 info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.66.0/sentry-cli-Linux-arm
#27 111.8 Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.66.0/sentry-cli-Linux-arm.
#27 111.8 Server returned 403: Forbidden.
#27 111.9 npm ERR! code ELIFECYCLE
#27 111.9 npm ERR! errno 1
#27 111.9 npm ERR! @sentry/cli@1.66.0 install: `node scripts/install.js`
#27 111.9 npm ERR! Exit status 1
#27 111.9 npm ERR! 
#27 111.9 npm ERR! Failed at the @sentry/cli@1.66.0 install script.
#27 111.9 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#27 112.0 
#27 112.0 npm ERR! A complete log of this run can be found in:
#27 112.0 npm ERR!     /root/.npm/_logs/2022-08-26T13_45_44_418Z-debug.log
------
executor failed running [/bin/sh -c npm ci  && npm run build:production]: exit code: 1
```

**Comment by tilusnet** [comment]
I notice Python 3.8 is configured; Python `armv7` wheel packages come with extensive Python 3.9 support, but no Python 3.8.
So ideally, a Python 3.9 config is favoured for Raspberry Pis.

Is there a strong reason for sticking with Python 3.8?

**Comment by farioas** [comment]
Moved to python 3.10. Please try to build now.

**Comment by tilusnet** [comment]
Hi.

piwheels doesn't support Python 3.10 yet, 3.9 is the build most widely supported atm.
Please see https://www.piwheels.org.

**Comment by sajarin** [comment]
Closing because I believe piwheels supports >=3.10 now. Feel free to comment and reopen if I'm wrong.
